---
- name: Install Tuned
  package: name=tuned state=latest

- name: Enable Tuned
  service: name=tuned state=started enabled=yes

- name: Check Tuned version
  shell: tuned-adm recommend &> /dev/null || echo -n "*fail"
  register: result

- set_fact:
    tuned_legacy: "{{ (result.stdout == '*fail') | ternary(true, false) }}"

- name: Set Tuned profile {{ tuned_profile }}
  command: tuned-adm profile {{ tuned_profile }}
