---
- name: Install Tuned
  package: name=tuned state=latest

- name: Enable Tuned
  service: name=tuned state=started enabled=yes

- name: Get list of available Tuned profiles
  shell: tuned-adm list | tail -n +2 | head -n -1 | cut -d' ' -f2
  register: profiles

- set_fact:
    tuned_available_profiles: "{{ profiles.stdout_lines }}"

- name: Check Tuned version / get recommended profile
  shell: tuned-adm recommend 2> /dev/null || echo -n " *fail"
  register: recommend

- set_fact:
    tuned_legacy: "{{ (recommend.stdout == ' *fail') | ternary(true,false) }}"

- set_fact:
    tuned_recommended_profile: "{{ (recommend.stdout == ' *fail') | ternary('',recommend.stdout) }}"

- name: Set Tuned profile {{ tuned_profile }}
  command: tuned-adm profile {{ tuned_profile }}
